### ISSUE TITLE
No 'Gift from the Mausoleum' tech

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#2]
I seem to be somewhat stuck with this mod. I've progressed the Mausoleum to level 5. When hovering it says check the 'gift from the Mausoleum' tech icon, but I see no such icon. It should be listed among the researched technologies I presume, but it isn't there. Am I missing something? In all 5 playthroughs so far I can't seem to do anything else but ascend and start over, because I keep getting stuck at the point where researches require over 100 Insight but I'm capped at 100. Currently the Mausoleum requires Mana to complete, but I don't know how to obtain that. I have no researches I can do or anything. I kept thinking I'm doing something wrong or missing something, but now I'm starting to wonder... could there be something wrong with my game?

**Comment by plasma4** [comment]
Ok, that's pretty strange: I haven't heard of that before. What's supposed to happen is that you gain the trait, and this trait unlocks a wizardry condition:
```js
if (G.achievByName['mausoleum'].won >= 1 && !G.has('a gift from the mausoleum')) { G.gainTech(G.techByName['a gift from the mausoleum']); }
```

I can think of a few potential problems:
- The game isn't running the "new game" function
- Somehow the mausoleum level is not working because of a unit misplacement/other rare programming oversight?
- Some other wild problem is happening with `gainTrait`

I haven't heard of this before, but can you try to export the save and send the uploaded text file over?
After your save a copy of your save (so I can figure out what is happening), you can try to run this script:
```js
G.gainTech(G.techByName['a gift from the mausoleum'])
```
After that, try reloading. I'm not sure why exactly that has happened: it may take a while for me to get to the bottom of this. Thanks for telling me!

**Comment by plasma4** [comment]
Also, are you using the file version or the online version? It might have to do with the file edition having some funky problems.

**Comment by JanMiddelkoop** [comment]
I'm using
https://file.garden/ZmatEHzFI2_QBuAF/magixUtils.js
https://file.garden/ZmatEHzFI2_QBuAF/magix.js

Not sure which version that is. Unfortunately I cannot provide you my save file, as I've (accidentally) wiped it trying to get more information.

**Comment by JanMiddelkoop** [comment]
I can't reproduce it anymore either.

**Comment by plasma4** [comment]
Hmm...all right then. Maybe an old version of the mod had a weird issue with reloading or something? If it's not happening now then that's a good sign.
