### ISSUE TITLE
Essential Conversion Tank no longer converts Influence after Smartness of Essentials tech

### ISSUE THREAD

**Issue by JanMiddelkoop** [plasma4/magix-fix#9]
There is a problem with this commit:
https://github.com/plasma4/magix-fix/commit/267fd548c9e21f6a82468fd2bd2e83d383d90f37

This disables conversion of Influence into Influence II after both techs "Essential conversion tank overclock I" and "Smartness of essentials" are obtained. There is no line that converts Influence to Influence II when both techs are obtained. Also there is now double culture gathering when both techs "People of the arts II" and "Smartness of essentials" are obtained.

While the commit linked above does fix the gathering of Faith II when "People of the arts II" is obtained, it breaks the conversion of Influence II.

**Comment by plasma4** [comment]
Thanks so much for your help! It should be fixed in the latest commit.
(By the way, if you ever find any more issues that have to do with incorrect conversion, I think it would be easier for you if you just went to [the Magix wiki](https://plasma4.github.io/magix-fix/magix-wiki.html) and look for any things that are off from there rather than having to spend forever looking at the commits or code.)

thanks for helping out again **:)**

**Comment by JanMiddelkoop** [comment]
But I like looking at code! ;-)

And to be honest, I find the javascript code (even though it's a bit spaghetti) much more comfortable to digest than the wiki.

**Comment by plasma4** [comment]
All right :p
sometimes i like looking at code too lol
